### ISSUE TITLE
Prepare and release version 0.1.0

### ISSUE THREAD

**Issue by dsleiter** [agencyenterprise/ndx-nirs#10]
TODO:
1. verify dependencies
2. verify `setup.py` configurations
3. remove no-longer-needed template instructions (such as NEXTSTEPS.md)
4. verify changelog
5. tag version
6. push release to PyPI

**Comment by sumner15** [comment]
3b. another example is `ndx-nirs/docs/readme.md`
7. remove text descriptions of version (I.e. `alpha` or `beta`), e.g. `ndx-nirs/docs/source/release_notes.rst` lists `beta` & `ndx-nirs/docs/source/conf.py` lists `alpha`

**Comment by dsleiter** [comment]
Release v0.1.0: https://github.com/agencyenterprise/ndx-nirs/releases/tag/v0.1.0

**Comment by dsleiter** [comment]
PyPI: https://pypi.org/project/ndx-nirs/
